// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetlekarz.Services;

namespace dotnetlekarz.Migrations
{
    [DbContext(typeof(DocDbContext))]
    partial class DocDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("dotnetlekarz.Models.UserModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("login")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<int>("role")
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("surname")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dotnetlekarz.Models.VisitModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("doctorid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("visitorid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("doctorid");

                    b.HasIndex("visitorid");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("dotnetlekarz.Models.VisitModel", b =>
                {
                    b.HasOne("dotnetlekarz.Models.UserModel", "doctor")
                        .WithMany()
                        .HasForeignKey("doctorid");

                    b.HasOne("dotnetlekarz.Models.UserModel", "visitor")
                        .WithMany()
                        .HasForeignKey("visitorid");
                });
#pragma warning restore 612, 618
        }
    }
}
